# Generated by Django 6.0.3 on 2026-03-21 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_cocktails', to=settings.AUTH_USER_MODEL),
        ),
    ]
